version: '3.3'

services:

  postgres-server:
    container_name: postgres-server
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=toor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: "host"

  spring-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - 8080:8080
    depends_on:
      - postgres-server
    network_mode: "host"

